main: me.flugel.main.Main
author: SneakFlugelo
version: 0.1
api-version: 1.16
name: EssencialMC
depend: [Vault]
commands:
  gm:
  gmc:
  gms:
  gme:
  fly:
  tell:
  kick:
  speed:
  op:
  settp:
  survival:
  tpa:
  tpaccept:
  sorteio:
  tpadeny:
  luz:
  inv:
  ajuda:
  tickets:
  ajudaClaim:
  voltar:
  ban:
  unban:
  echest:
    aliases: [enderchest, ec]
  adm:
  aviso:

